version: "3"
services:
  maven:
    # Run pre-built maven image from docker library
    image: maven
    volumes:
      - $HOME/.m2:/root/.m2
      - /Users/sathyasankar/workspace/hello-world-api:/app
    working_dir: /app
volumes:
  maven-repository:
