steps:
  - label: ":maven: :package:"
    command: mvn clean deploy -DmuleDeploy
    artifact_paths: "target/*.jar"
    plugins:
      - docker-compose#v1.5.2:
          run: maven
          config: .buildkite/docker-compose.yml
