steps:
  - label: "Echo Step"
    command: "echo 'Hello World'"

  - label: "Container Step"
    plugins:
      - docker#v5.9.0:
          image: "sathyadocker/pipeline-builder:latest"
          always-pull: true
          command: ["pipeline"]