env:
  ECHO_VAL: "Hello World"
steps:
  - label: ":maven: :package:"
    command: mvn clean deploy -DmuleDeploy
    artifact_paths: "target/*.jar"
    plugins:
      - docker#v5.9.0:
          image: maven:3.8.4-jdk-8
